/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <unistd.h>
#include <cmath>
/* Header for class com_dhnns_opencv_test_CVFunc */
#include <iostream>
#include <string>

#include "opencv2/opencv.hpp"

#ifndef _Included_com_dhnns_opencv_test_CVFunc
#define _Included_com_dhnns_opencv_test_CVFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhnns_opencv_test_CVFunc
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_dhnns_opencv_1test_CVFunc_ConvertRGBtoGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_dhnns_opencv_test_CVFunc
 * Method:    PCACompute
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_dhnns_opencv_1test_CVFunc_PCACompute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dhnns_opencv_test_CVFunc
 * Method:    flite_test
 * Signature: (J)V
 */

#ifdef __cplusplus
}
#endif
#endif
